name: Update Tree

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  MY_GITHUB_OWNER: ${{ secrets.MY_GITHUB_OWNER }}

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update Structure Config with Placeholders
        run: |
          # Aggiorna structure.config.json salvando la struttura corrente con placeholder
          node -e "require('./src/utils/compareStructure').saveStructure(process.cwd(), 'structure.config.json', ['node_modules', '.git'])"

      - name: Generate File Tree
        run: |
          # Genera file_tree.txt basandosi sulla configurazione aggiornata
          node -e "require('./src/utils/fileTreeGenerator').writeFileTree(process.cwd(), 'file_tree.txt', { compressDirs: ['node_modules', '.git'] }, './description.json')"