name: Update Tree

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  MY_GITHUB_OWNER: ${{ secrets.MY_GITHUB_OWNER }}

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update Structure Config with Placeholders
        run: |
          node -e "import('./src/utils/compareStructure.js').then(mod => mod.saveStructure(process.cwd(), 'structure.config.json', ['node_modules', '.git'])).catch(err => { console.error(err); process.exit(1); })"

      - name: Auto-update Descriptions
        run: |
          node -e "import('./scripts/autoUpdateDescriptions.js').then(() => console.log('Descriptions updated successfully.')).catch(err => { console.error(err); process.exit(1); })"

      - name: Generate File Tree
        run: |
          node -e "import('./src/utils/fileTreeGenerator.js').then(mod => mod.writeFileTree(process.cwd(), 'file_tree.txt', { compressDirs: ['node_modules', '.git'] }, './description.json')).catch(err => { console.error(err); process.exit(1); })"