name: Update Tree

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  MY_GITHUB_OWNER: ${{ secrets.MY_GITHUB_OWNER }}

on:
  push:
    branches:
      - main

jobs:
  update-tree:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Ensures every step runs in the repository root.
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update Structure Config with Placeholders
        run: |
          echo "Working directory: $(pwd)"
          echo "Updating structure.config.json..."
          node -e "import('./src/utils/compareStructure.js').then(mod => { mod.saveStructure(process.cwd(), 'structure.config.json', ['node_modules', '.git']); console.log('Structure config updated successfully.'); }).catch(err => { console.error('Error updating structure config:', err); process.exit(1); })"

      - name: Auto-update Descriptions
        run: |
          echo "Working directory: $(pwd)"
          echo "Updating description.json..."
          node scripts/autoUpdateDescriptions.js

      - name: Generate File Tree
        run: |
          echo "Working directory: $(pwd)"
          echo "Generating file_tree.txt..."
          node -e "import('./src/utils/fileTreeGenerator.js').then(mod => { mod.writeFileTree(process.cwd(), 'file_tree.txt', { compressDirs: ['node_modules', '.git'] }, './description.json'); console.log('File tree generated successfully.'); }).catch(err => { console.error('Error generating file tree:', err); process.exit(1); })"