name: Update Variables

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora (modifica la frequenza se necessario)
  workflow_dispatch:

jobs:
  update-variables:
    runs-on: ubuntu-latest

    env:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      # Flag per aggiornare i vari servizi automaticamente
      UPDATE_GITHUB_VARS: "true"
      UPDATE_NETLIFY_VARS: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update All Variables
        run: node scripts/updateAllVars.js